<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HOME" failures="1" tests="3" name="testng_listener.xml" time="0.069" errors="0" timestamp="2023-12-10T14:26:07 IST">
  <testcase classname="testNG.ListnersDemo" name="f" time="0.011"/>
  <testcase classname="testNG.ListnersDemo" name="f1" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testNG.ListnersDemo.f1(ListnersDemo.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase classname="testNG.ListnersDemo" name="f2" time="0.0">
    <skipped/>
  </testcase> <!-- f2 -->
</testsuite> <!-- testng_listener.xml -->
